spring:
  rabbitmq:
    host: rabbitmq.default.svc.cluster.local
    password: admin
    port: 5672
    username: admin
    exchange: movie.exchange
    queue: movie.queue
    routingkey: movie.routingkey